ktor:
  deployment:
    host: "$HOST:0.0.0.0"
    port: "$PORT:8080"
  application:
    modules:
      - me.kuku.telegram.ktor.ServerKt.config
      - me.kuku.telegram.ktor.KoinKt.koin
      - me.kuku.telegram.ktor.ExposedKt.exposed
      - me.kuku.telegram.ktor.TelegramBotKt.telegramBot
      - me.kuku.telegram.ktor.QuartzKt.quartz

telegram-bot:
  token: "$TELEGRAM_TOKEN:"
  username: "$TELEGRAM_USERNAME:"
  api: "$TELEGRAM_API:"